2025-10-02 10:36:41,947 - logger - INFO - ðŸ”¹ Baixando anexos XML do e-mailâ€¦ - email_handler.py - 16:
2025-10-02 10:37:21,619 - logger - WARNING - Produto veio como lista, pegando o primeiro elemento. - web_scraper.py - 104:
2025-10-02 10:37:21,622 - logger - INFO - Fallback Playwright para ESPACADOR 2,0MM - web_scraper.py - 143:
2025-10-02 10:37:25,188 - logger - WARNING - Produto veio como lista, pegando o primeiro elemento. - web_scraper.py - 104:
2025-10-02 10:37:25,773 - logger - INFO - Cache salvo. - web_scraper.py - 28:
2025-10-03 11:18:22,156 - logger - INFO - ðŸ”¹ Baixando anexos XML do e-mailâ€¦ - email_handler.py - 16:
2025-10-03 11:18:52,447 - logger - INFO - Arquivo salvo: notas/NFe35251038203316000234550020001099261902532320.xml - email_handler.py - 26:
2025-10-03 11:18:54,799 - logger - INFO - Arquivo salvo: notas/NFe35251004648461000207550020033060421254151236.xml - email_handler.py - 26:
2025-10-03 11:19:04,397 - logger - WARNING - Produto veio como lista, pegando o primeiro elemento. - web_scraper.py - 104:
2025-10-03 11:19:04,401 - logger - INFO - Fallback Playwright para ESPACADOR 2,0MM - web_scraper.py - 143:
2025-10-03 11:19:26,253 - logger - WARNING - Produto veio como lista, pegando o primeiro elemento. - web_scraper.py - 104:
2025-10-03 11:19:36,043 - logger - INFO - Cache salvo. - web_scraper.py - 28:
2025-10-03 11:51:13,714 - logger - INFO - ðŸ”¹ Baixando anexos XML do e-mailâ€¦ - email_handler.py - 16:
2025-10-03 11:52:03,249 - logger - WARNING - Produto veio como lista, pegando o primeiro elemento. - web_scraper.py - 104:
2025-10-03 11:52:03,252 - logger - INFO - Fallback Playwright para JOELHO ESG 100X90 - web_scraper.py - 143:
2025-10-03 11:52:09,478 - logger - WARNING - Produto veio como lista, pegando o primeiro elemento. - web_scraper.py - 104:
2025-10-03 11:52:09,991 - logger - ERROR - Erro ao fazer request para https://www.construdigi.com.br/produto/180249/180249: HTTPSConnectionPool(host='www.construdigi.com.br', port=443): Read timed out. (read timeout=10) - web_scraper.py - 46:
Traceback (most recent call last):
  File "/home/lucas-silva/github/auto_shopee/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
  File "/home/lucas-silva/github/auto_shopee/venv/lib/python3.10/site-packages/urllib3/connection.py", line 565, in getresponse
    httplib_response = super().getresponse()
  File "/usr/lib/python3.10/http/client.py", line 1375, in getresponse
    response.begin()
  File "/usr/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.10/ssl.py", line 1303, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.10/ssl.py", line 1159, in read
    return self._sslobj.read(len, buffer)
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lucas-silva/github/auto_shopee/venv/lib/python3.10/site-packages/requests/adapters.py", line 644, in send
    resp = conn.urlopen(
  File "/home/lucas-silva/github/auto_shopee/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 841, in urlopen
    retries = retries.increment(
  File "/home/lucas-silva/github/auto_shopee/venv/lib/python3.10/site-packages/urllib3/util/retry.py", line 474, in increment
    raise reraise(type(error), error, _stacktrace)
  File "/home/lucas-silva/github/auto_shopee/venv/lib/python3.10/site-packages/urllib3/util/util.py", line 39, in reraise
    raise value
  File "/home/lucas-silva/github/auto_shopee/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    response = self._make_request(
  File "/home/lucas-silva/github/auto_shopee/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 536, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/home/lucas-silva/github/auto_shopee/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 367, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='www.construdigi.com.br', port=443): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lucas-silva/github/auto_shopee/web_scraper.py", line 36, in _processar_com_requests
    response = requests.get(url, headers=self.headers, timeout=10)
  File "/home/lucas-silva/github/auto_shopee/venv/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/home/lucas-silva/github/auto_shopee/venv/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/lucas-silva/github/auto_shopee/venv/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/lucas-silva/github/auto_shopee/venv/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/lucas-silva/github/auto_shopee/venv/lib/python3.10/site-packages/requests/adapters.py", line 690, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='www.construdigi.com.br', port=443): Read timed out. (read timeout=10)
2025-10-03 11:52:10,002 - logger - INFO - Fallback Playwright para CHAVE TORX CRV L C/GUIA T09/T50 10PC PRO - web_scraper.py - 143:
2025-10-03 11:52:12,918 - logger - INFO - Cache salvo. - web_scraper.py - 28:
